# Generated by Django 5.1.2 on 2024-10-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('fname', models.CharField(blank=True, max_length=8, null=True)),
                ('minit', models.CharField(blank=True, max_length=2, null=True)),
                ('lname', models.CharField(blank=True, max_length=8, null=True)),
                ('ssn', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('bdate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=27, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('salary', models.IntegerField()),
                ('super_ssn', models.CharField(blank=True, max_length=9, null=True)),
                ('dno', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
